### ISSUE TITLE
Update GET requests for light with more efficient method

### ISSUE THREAD

**Issue by dosterz97** [dosterz97/zephyr#1]
Right now the light is updated from the site very inefficiently using GET requests to turn the light on and off, which will prevent scaling at a larger level. This should be replaced with a more efficient method.

**Comment by dosterz97** [comment]
Need to sync up with Dylan, but first research alternatives to the GET request and look for ways to increase the efficiency of the code.

**Comment by DylanLade** [comment]
app.py is set to listen for the url to change to either "/on" or "/off" it isn't actually transferring any information, it is being used as a trigger for the light. Feeding any info other than on or off into the url will have no effect on the program because app.py will always load lights.html.
