### ISSUE TITLE
Create Designs for webpage UI

### ISSUE THREAD

**Issue by dosterz97** [dosterz97/zephyr#3]
Some basic structure designs for both mobile and desktop view nothing too complicated but simple and clean

**Comment by jcbasa** [comment]
### To do

* Create a static directory.
* Create a template directory.
* Create the header.html files. Link style.css inside header as a stylesheet.
* Create images to use for webpage and put into static folder.
* Create style.css file inside directory. 
* Edit css file to create a good design OR include a CSS boilerplate.

### Back-log

* Install CSS Boilerplate with responsive modules: https://purecss.io/
* Maybe implement sketch here: https://github.com/dosterz97/zephyr/tree/master/views

**Comment by jcbasa** [comment]
The directories now exist in the repository, including the CSS framework file that will be used.
